### ISSUE TITLE
schema.js throws errors when a newer version of Joi is already included with the project

### ISSUE THREAD

**Issue by chronosis** [baseprime/dynamodb#10]
If you are already including a newer version of Joi (e.g 10.x.x) in a project and attempt to use `dynamodb` as well, then Node throws the following runtime exceptions:

```
/node_modules/dynamodb/lib/schema.js:23
  indexes   : Joi.array().includes(internals.secondaryIndexSchema),
                          ^

TypeError: Joi.array(...).includes is not a function
```

This is because `array().includes()` was removed from the Joi library in favor of the `array.items()` method.  So that this library can interop properly with the newest version of Joi the method must be changed to use the `array().items()` on lines 23, 147, 153, and, 158. 

**For example** (line 23): 
```js  
indexes   : Joi.array().items(internals.secondaryIndexSchema),
```
This should allow the library to be updated to Joi v10 in package.json as well (recommended since the included version is more than 2 years old):

```json
    "joi": "^10.6.0",    //"joi": "5.x.x",
```

This is related to the Pull Request in #8

**Comment by RoyHP** [comment]
Having this issue as well

**Comment by chronosis** [comment]
Project appear abandoned, closing ticket
