### ISSUE TITLE
Putting an item?

### ISSUE THREAD

**Issue by atelic** [baseprime/dynamodb#13]
Looking through the documentation and source, it doesn't look like this library provides functionality similar to aws' `putItem`. Is there a way to simulate this behavior?

My use case is that I want to create a new item, replace an old one with the same primary key or insert a new one if that primary key does not exist.

**Comment by hammadzz** [comment]
Any reason you can't go to the more popular fork of vogels: https://github.com/clarkie/dynogels

**Comment by atelic** [comment]
Outdated
