### ISSUE TITLE
AWS Saml login doesn't work

### ISSUE THREAD

**Issue by soliveira-nascent** [baseprime/dynamodb#16]
It looks like environment variables are not being detected by the AWS client. I have `AWS_PROFILE=assumed_role` exported and I should be authenticated automatically, however I get the following error: 

```{"cause":{"message":"Missing credentials in config","code":"CredentialsError"```

I've updated the AWS SDK version in package.json and this fixed the issue. It looks like this package is using an older version of the SDK that does not support credentials through these environment variables. I've made a PR for this fix

**Comment by hammadzz** [comment]
did you try opening an issue on dynogels repo?

**Comment by soliveira-nascent** [comment]
How is it related to this project?

**Comment by hammadzz** [comment]
@soliveira-nascent this repo just seems to be a quiet fork of https://github.com/clarkie/dynogels which is a fork of vogels because that repos admin ghosted away. So I would just go to a better maintained fork than what feels like a stolen credit fork.

**Comment by baseprime** [comment]
@soliveira-nascent @hammadzz Please see newest release (https://github.com/baseprime/dynamodb/pull/22). Feel free to run tests to verify its compatibility. 👍
