### ISSUE TITLE
Where's vogel?

### ISSUE THREAD

**Issue by gEndelf** [baseprime/dynamodb#3]
@baseprime
- Did you see that https://github.com/ryanfitz/vogels?
- what about licence?

it seems this project is clone of **vogel** with license violation

**Comment by gEndelf** [comment]
@ryanfitz did you see that?

**Comment by baseprime** [comment]
@gEndelf Please see LICENSE.md. I'm already in contact with @ryanfitz. 

If you truly think this is a license violation, then you truly don't understand the meaning of the Open Source initiative.

**Comment by gEndelf** [comment]
yes, I read it
