### ISSUE TITLE
Region Support 

### ISSUE THREAD

**Issue by salimusta** [baseprime/dynamodb#4]
Using dynamo.AWS.config.update({region: "REGION"}); // region must be set is not Working.

Anyone with the same issue?

**Comment by salimusta** [comment]
Was able to specify the Region, By specifying the endPoint on creation. Should we update the doc?

**Comment by andrewmunsell** [comment]
Specifying the region works fine for me using the syntax you described.

**Comment by Geeza** [comment]
I'm having the exact same issue as @salimusta 

```
const dynamo = require('dynamodb')
dynamo.AWS.config.update({ region: "eu-central-1" })
dynamo.createTables(function(err) {
  if (err) {
    console.log('Error creating tables: ', err)
  } else {
    console.log('Tables has been created')
  }
})
```

Results in `Error creating tables:  { ConfigError: Missing region in config`

**Comment by borys-kupar** [comment]
I am experiencing the same problem. @Geeza, did you find a solution?
