### ISSUE TITLE
Upsert support?

### ISSUE THREAD

**Issue by abdurahmanadilovic** [baseprime/dynamodb#48]
Hi, is there a support for upsert option (if record does not exist create it, if it does just update it) when doing updates?

**Comment by efortes** [comment]
You can use `EventModel.create`. There should be an option to auto create.

**Comment by abdurahmanadilovic** [comment]
Upsert works by default with the update method

**Comment by valeeum** [comment]
@abdurahmanadilovic 

Is it possible tot get createdAt and updatedAt hooks to work using update while upsertinig?
