### ISSUE TITLE
 Error: Cannot find module './build/Release/DTraceProviderBindings'

### ISSUE THREAD

**Issue by itinsley** [baseprime/dynamodb#50]
I get the following error on a clean project with no other dependencies using NPM.

# System info
ProductName:	Mac OS X
ProductVersion:	10.13.4
BuildVersion:	17E199

# Stacktrace
    { Error: Cannot find module './build/Release/DTraceProviderBindings'
        at Function.Module._resolveFilename (module.js:538:15)
        at Function.Module._load (module.js:468:25)
        at Module.require (module.js:587:17)
        at require (internal/module.js:11:18)
        at Object.<anonymous> (/Users/iantinsley/work/loop-plus/dynamo-issue/node_modules/dtrace-provider/dtrace-provider.js:17:23)
        at Module._compile (module.js:643:30)
        at Object.Module._extensions..js (module.js:654:10)
        at Module.load (module.js:556:32)
        at tryModuleLoad (module.js:499:12)
        at Function.Module._load (module.js:491:3) code: 'MODULE_NOT_FOUND' }
    { Error: Cannot find module './build/default/DTraceProviderBindings'
        at Function.Module._resolveFilename (module.js:538:15)
        at Function.Module._load (module.js:468:25)
        at Module.require (module.js:587:17)
        at require (internal/module.js:11:18)
        at Object.<anonymous> (/Users/iantinsley/work/loop-plus/dynamo-issue/node_modules/dtrace-provider/dtrace-provider.js:17:23)
        at Module._compile (module.js:643:30)
        at Object.Module._extensions..js (module.js:654:10)
        at Module.load (module.js:556:32)
        at tryModuleLoad (module.js:499:12)
        at Function.Module._load (module.js:491:3) code: 'MODULE_NOT_FOUND' }
    { Error: Cannot find module './build/Debug/DTraceProviderBindings'
        at Function.Module._resolveFilename (module.js:538:15)
        at Function.Module._load (module.js:468:25)
        at Module.require (module.js:587:17)
        at require (internal/module.js:11:18)
        at Object.<anonymous> (/Users/iantinsley/work/loop-plus/dynamo-issue/node_modules/dtrace-provider/dtrace-provider.js:17:23)
        at Module._compile (module.js:643:30)
        at Object.Module._extensions..js (module.js:654:10)
        at Module.load (module.js:556:32)
        at tryModuleLoad (module.js:499:12)
        at Function.Module._load (module.js:491:3) code: 'MODULE_NOT_FOUND' }
    Readable {
      _readableState: 
      ReadableState {
        objectMode: true,
        highWaterMark: 16,
        buffer: BufferList { head: null, tail: null, length: 0 },
        length: 0,
        pipes: null,
        pipesCount: 0,
        flowing: null,
        ended: false,
        endEmitted: false,
        reading: false,
        sync: true,
        needReadable: false,
        emittedReadable: false,
        readableListening: false,
        resumeScheduled: false,
        destroyed: false,
        defaultEncoding: 'utf8',
        awaitDrain: 0,
        readingMore: false,
        decoder: null,
        encoding: null },
      readable: true,
      domain: null,
      _events: {},
      _eventsCount: 0,
      _maxListeners: undefined,
      promise: [Function],
      _read: [Function] }

**Comment by jarrod-marshall** [comment]
Same issue as well. Completely new project and the same thing happens.

**Comment by jonnyshaw89** [comment]
+1

**Comment by NiciusB** [comment]
Same thing happened to me.
When I reinstalled everything, I noticed a message from "dtrace-provider"

    ---------------
    Building dtrace-provider failed with exit code 1 and signal 0
    re-run install with environment variable V set to see the build output
    ---------------


Going through the common issues in https://www.npmjs.com/package/dtrace-provider#troubleshooting-build-issues helped me fix the problem, and after reinstalling everything, it works flawlessly

**Comment by naishe** [comment]
Can confirm: works in Linux, fails in OS X High Sierra.

**Comment by jasonfutch** [comment]
Temporary work around that worked for me until they fix this package...

"I got rid of this error by running `rm -rf node_modules` and then running `npm i --no-optional` with `dtrace-provider` in my dependencies. It was at version 0.8.7."

https://stackoverflow.com/questions/19868938/how-i-can-work-with-amazons-dynamodb-local-in-node

**Comment by alailsonribeiro** [comment]
**For me working fine in app root:**
```
rm -rf node_modules \
npm install --no-optional
```

**Comment by MickL** [comment]
Hey guys!

The dependencies of this module are outdated and dont work with latest node version. There is an open PR https://github.com/baseprime/dynamodb/pull/70 that fixes that, but seems like this module is no more maintained. You can use my fork for now:

`npm install mickl/dynamodb @hapi/joi --save`

Feel free to make PR's there as long as this project is not maintained. I am also working on defining typings for use in TypeScript projects.

**Comment by AdamTyler** [comment]
@MickL I was using your fork to account help with the numerous issues with this package being outdated but it appears you no longer are maintaining that repo... is there a reason why? It seems the PR #70 is still open

**Comment by MickL** [comment]
Sorry I just deleted that repo and forgot about this issue. According to @baseprime this project is maintained as he said in the PR #70, still he does no effort in merging the PR or fixing it himself. Neither does he give advice how we can get the PR merged.

I ended up using https://github.com/dynamoose/dynamoose instead

**Comment by AdamTyler** [comment]
ah bummer. It is unfortunate that this project is supposedly maintained but so much of it is out of date.

I'll take a look into dynamoose. For the time being I dropped in @line0 fork from the PR so my builds wouldn't fail 😞

**Comment by baseprime** [comment]
@AdamTyler This package _is_ maintained. If the fixes are there, along with tests that pass, it’ll usually end up in the codebase. However, very few people have been able to help out in that regard. **None of the PRs that have been submitted currently pass tests**. 

It’s important to realize that this package is used by tens of thousands of projects. You can’t just throw code into those projects without making sure everything is well tested and things won’t break.

**Comment by MickL** [comment]
> It’s important to realize that this package is used by tens of thousands of projects. You can’t just throw code into those projects without making sure everything is well tested and things won’t break.

Currently it does not work at all, so it is broken already. Further we asked you a few times what (more) tests you need but you did not make the effort to even reply.

**Comment by baseprime** [comment]
These tests need to pass:
```npm test```

Then you need to add test cases for the code you’re adding. It’s not that difficult.

**Comment by line0** [comment]
> @AdamTyler This package _is_ maintained. If the fixes are there, along with tests that pass, it’ll usually end up in the codebase. However, very few people have been able to help out in that regard. **None of the PRs that have been submitted currently pass tests**.

My PR #70 contains the necessary adjustments to make all tests pass on my end. I have even attached test logs as per your request. How do you expect me to resolve the issues on your secret CI environment with zero details to go on?

**Comment by baseprime** [comment]
@line0 Thank you for adding those. I've merged latest CI config to your remote repo. Please review: https://github.com/line0/dynamodb/pull/4

**Comment by baseprime** [comment]
@line0 changes in latest release include passing tests. If anyone in this thread would like to see how to contribute, please refer to it. 

@MickL
