### ISSUE TITLE
Schema serializer is broken for all set items

### ISSUE THREAD

**Issue by devonhumes** [baseprime/dynamodb#55]
The serializer was broken in commit https://github.com/baseprime/dynamodb/commit/d0543ae49eff4662c8bee4dc774d6cbc5a69437e. 

Prior to this commit, schemas that included DynamoDB sets correctly parsed those values. For some examples of this problem please see the tests. There are currently 16 failing tests that deal with this issue.

Example test output
```
      AssertionError: expected { Object (foo, date, ...) } to deeply equal { Object (foo, date, ...) }
      + expected - actual

         "date": "DATE"
         "flag": "BOOL"
         "foo": "S"
         "items": "L"
      -  "nums": [
      -    {
      -      "invalids": [null]
      -      "type": [null]
      -    }
      -  ]
      +  "nums": "NS"
       }
```

This affects `1.2.0`, but not `1.1.2`.

**Comment by line0** [comment]
This also breaks serialization of simple array structures defined by a schema such as 
```javascript
const schema = Joi.object().required().keys({
  resolution: Joi.array().length(2).items(Joi.number().integer().required()).required(),
});
```
The array items get serialized into empty objects, so with an object like 
```javascript
{
  resolution: [1920, 1080],
}
```
 you end up with 
```json
{
  "resolution": [{}, {}]
}
```

**Comment by jcrugzz** [comment]
I published a [temporary fork](https://www.npmjs.com/package/dynamodb-x) that integrates the fix found in https://github.com/baseprime/dynamodb/pull/53 until author has time.

**Comment by baseprime** [comment]
@jcrugzz @devonhumes Landed in latest release
