### ISSUE TITLE
Add automated testing

### ISSUE THREAD

**Issue by MickL** [baseprime/dynamodb#77]
When making a pull request it should automatically get tested by a tool like Travis CI.

**Comment by baseprime** [comment]
CircleCI is already set up.

**Comment by MickL** [comment]
Weird, I dont see any tests on PRs: https://github.com/baseprime/dynamodb/pull/70

**Comment by MickL** [comment]
Also, are you sure you didnt mean travis ci? Seems like it is not running automatically on PRs or does it?

**Comment by baseprime** [comment]
@MickL Yes, I know the difference between Travis and CircleCI.

Tests run on every commit in any branch. I can clearly see which tests pass and which tests fail. You aren’t a collaborator yet so you can’t see the test results in CircleCI, and we are not switching to TravisCI any time soon.
