### ISSUE TITLE
Why are tables pluralised by default?

### ISSUE THREAD

**Issue by jaitaiwan** [baseprime/dynamodb#83]
Hi,

Why is it on line https://github.com/baseprime/dynamodb/blob/72dc874a1de4d500f5effa383a88255049f00632/lib/index.js#L71 table names are pluralised by default? I've just spent countless hours on this trying to find out why I was getting a "ResourceNotFoundException" error 😅 

Happy to do a PR and update documentation to turn this off.

Thanks

**Comment by bitconquer** [comment]
I agree with @jaitaiwan, this is not very intuitive and takes away control over an important parameter for the developer. Having an option to disable this conversion would be handy.

**Comment by AbirAbbas** [comment]
This is common amongst ORMs

**Comment by jaitaiwan** [comment]
Not interested in giving the user control of this or document it? It’s also common for ORMs to give users the ability to override default behaviour like this.
