### ISSUE TITLE
No credit to Vogels or Dynogels

### ISSUE THREAD

**Issue by barendb** [baseprime/dynamodb#89]
@baseprime Having looked through code this and being intimately familiar with [Vogels](https://github.com/ryanfitz/vogels) and [Dynogels](https://github.com/clarkie/dynogels) it struck me there is quite a lot copied from those libraries, but I can't see any credit to those authors or reference to those libraries. 

![](https://media.giphy.com/media/l0MYJgbJrTy2iRvGw/giphy.gif)

**Comment by baseprime** [comment]
@barendb Vogels/Ryan clearly has credit in the license, in the README, package.json, and in the commits. What else do you expect me to add?

Vogels was also not maintained anymore when I took over. I also had a dialogue with Ryan before I took over. 

Did you just come here to be a pain in the ass? Do you even understand the first thing about maintaining a widely-used open source package?

I think the shame belongs to you.
