### ISSUE TITLE
Library unmaintained?

### ISSUE THREAD

**Issue by satanch** [baseprime/dynamodb#98]
As I see last commit was almost a year ago. Is this library unmaintained?
Maybe a good fork is needed. I can see some significant issues and requests:

https://github.com/baseprime/dynamodb/issues/45
https://github.com/baseprime/dynamodb/issues/49
https://github.com/baseprime/dynamodb/issues/1
https://github.com/baseprime/dynamodb/issues/79

So this library should be forked or marked as deprecated in my opinion. In fact - sad things happens, library authors loose opportunity to maintain library sometimes. Wanted to use this library in production, but this library seems to be dead, or will be dead in few months.

**Comment by Disfractal** [comment]
Ya running into this now. Scanning should support secondary indexes now but this package doesn't might have to fork it.

**Comment by baseprime** [comment]
@Disfractal This library is maintained, although there haven’t been many PRs to help bring it up to date.
